version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - IMAGE_TAG=latest
      - docker build -t brain-tasks-app:$IMAGE_TAG .
      - docker tag brain-tasks-app:$IMAGE_TAG <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG
  post_build:
    commands:
      - docker push <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:$IMAGE_TAG
      - echo '[{"name":"brain-container","imageUri":"<your-account-id>.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - appspec.yml
    - scripts/update-kubeconfig.sh
    - scripts/deploy-to-eks.sh
    - imagedefinitions.json
